# Deployment + service setup for mongoDB (with PVC - Persistance Volume Claim)

# PVC 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: microservices-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: microservices-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          emptyDir: {}
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: microservices-demo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
